### ISSUE TITLE
Incomplet support of charts options

### ISSUE THREAD

**Issue by noraj** [picatz/chart_js#4]
I was trying to use the bar chart but I saw that unfortunately very few optiosn are supported: https://github.com/picatz/chart_js/tree/master/lib/chart_js/chart/bar_chart

https://www.chartjs.org/docs/latest/charts/bar.html#horizontal-bar-chart

For example it is impossible to configure barThickness.

**Comment by picatz** [comment]
I'm not sure how much effort I can dedicate to supporting all of the options, but I would be open to PRs in order to support more options. 🙇

**Comment by picatz** [comment]
I just added some [`method_missing`](https://github.com/picatz/chart_js/commit/fa5118b445dd27ebe0a91750fa14bfa7bddf77db) magic to catch unknown dataset options. This will allow you pass this options in either ruby-style `bar_thickness` or using [documented JS style options ](https://www.chartjs.org/docs/latest/charts/bar.html#barthickness)`barThickness`.

```ruby
ChartJS.bar do
  file "example.html"
  data do
    labels ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"]
    dataset "Apples" do
      color :random
      data [12, 19, 3, 5, 2, 3]
      bar_thickness 1
    end 
  end
end
```

Going to release this in version `1.1.1`.

**Comment by picatz** [comment]
Should be supported in version [`1.1.1`](https://rubygems.org/gems/chart_js/versions/1.1.1) 👍 

Please let me know if you have any issues. 🙏
