### ISSUE TITLE
Pi-Charts

### ISSUE THREAD

**Issue by noraj** [picatz/chart_js#5]
What are the difference between [Pi-Charts](https://github.com/picatz/Pi-Charts) and chart_js ?

**Comment by picatz** [comment]
`chart_js` provides a [DSL](https://en.wikipedia.org/wiki/Domain-specific_language)-style syntax to do roughly the same thing. In general, both of these were experiments in using Ruby to generate Chart.js visualizations. 

But, I tend to **not** use these gems anymore. These days I would much prefer to perform the client-side stuff in something like [Svelte](https://svelte.dev/) and then the backend API in Ruby or Go to feed the chart with information.

**Comment by noraj** [comment]
> These days I would much prefer to perform the client-side stuff in something like [Svelte](https://svelte.dev/) and then the backend API in Ruby or Go to feed the chart with information.

Seems like a good idea to build a web app. 

> But, I tend to **not** use these gems anymore.

I was more wishing to build a rubygems CLI tool that generates some charts rather than a web app. But maybe a CLI tool that opens a webapp on localhost is more suitable for visualization all will allow to sue numerous chart libs targeting RoR/Sinatra.

**Comment by picatz** [comment]
Totally agree with the webapp on localhost idea. 👍
